cmake_minimum_required(VERSION 3.28)
project(v2.0_all)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE Release)

set(SHARED src/shared/ar_valid.cpp src/shared/meniu.cpp src/shared/mokinio_info.cpp src/shared/rnd_generacija.cpp)
set(VECTOR src/vector/main_vector.cpp)
add_executable(v2.0_vector ${SHARED} ${VECTOR})
target_include_directories(v2.0_vector PRIVATE include)
add_executable(v2.0_test ${SHARED} src/test/testavimas.cpp)
target_include_directories(v2.0_test PRIVATE include)
add_executable(v2.0_grup ${SHARED} src/test/test_rusiavimas.cpp)
target_include_directories(v2.0_grup PRIVATE include)
add_executable(v2.0_rof ${SHARED} src/test/test_ro5.cpp)
target_include_directories(v2.0_rof PRIVATE include)